Documentation:
  Enabled: false

RedundantSelf:
  Enabled: false

LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: ruby19

AllCops:
  Includes:
    - Gemfile
    - Rakefile
  Excludes:
    - bin/**
